### ISSUE TITLE
Workspace actions broken on 3.36

### ISSUE THREAD

**Issue by rmader** [mpiannucci/gnome-shell-extended-gestures#81]
The switch workspace actions currently fail with the following error:
```
JS ERROR: Exception in callback for signal: activated: TypeError: Main.wm._actionSwitchWorkspace is not a function
_switchWorkspace@/home/robert/.local/share/gnome-shell/extensions/extendedgestures@mpiannucci.github.com/extension.js:201:17
```

Additionally the attempt seems to break something in GS until I switch the workspace by other means.

**Comment by DmitriyMurzin** [comment]
Not work on gnome 3.36 in ubuntu 20.04, install with error

```
JS ERROR: Extension extendedgestures@mpiannucci.github.com: TypeError: Clutter.DeviceManager is undefined
                                             _init@/home/bart/.local/share/gnome-shell/extensions/extendedgestures@mpiannucci.github.com/extension.js:41:29
                                             wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
                                             _Base.prototype._construct@resource:///org/gnome/gjs/modules/script/_legacy.js:18:10
                                             newClass@resource:///org/gnome/gjs/modules/script/_legacy.js:114:21
                                             enable@/home/bart/.local/share/gnome-shell/extensions/extendedgestures@mpiannucci.github.com/extension.js:246:22
                                             _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:161:32
                                             loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:312:26
                                             callback@resource:///org/gnome/shell/ui/extensionDownloader.js:216:39
                                             gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:106:13

```

**Comment by jburky** [comment]
> Not work on gnome 3.36 in ubuntu 20.04, install with error
> 
> ```
> JS ERROR: Extension extendedgestures@mpiannucci.github.com: TypeError: Clutter.DeviceManager is undefined
>                                              _init@/home/bart/.local/share/gnome-shell/extensions/extendedgestures@mpiannucci.github.com/extension.js:41:29
>                                              wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
>                                              _Base.prototype._construct@resource:///org/gnome/gjs/modules/script/_legacy.js:18:10
>                                              newClass@resource:///org/gnome/gjs/modules/script/_legacy.js:114:21
>                                              enable@/home/bart/.local/share/gnome-shell/extensions/extendedgestures@mpiannucci.github.com/extension.js:246:22
>                                              _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:161:32
>                                              loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:312:26
>                                              callback@resource:///org/gnome/shell/ui/extensionDownloader.js:216:39
>                                              gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:106:13
> ```

I got the same error on Fedora 32 Beta which also uses Gnome 3.36.

**Comment by rmader** [comment]
The bug you two are experiencing is already fixed (https://github.com/mpiannucci/gnome-shell-extended-gestures/commit/25f81b3f065299baecd1e7d20a3dade6aa471bbf) - maybe the update has not peen pushed to https://extensions.gnome.org/ ? @mpiannucci, have you pushed it already?
Otherwise please make sure to have updated your version.

Anyhow, the bug I'm experiencing is on master and a different one.

**Comment by DmitriyMurzin** [comment]
Thanks, latest version on https://extensions.gnome.org/ not working. Please add new version.

**Comment by RobertLemmens** [comment]
Can confirm that it broke on my machine as well when upgrading to gnome 3.36.1. Toggle overview works, but forward and backwards stopped working.

**Comment by spaceface777** [comment]
The `_actionSwitchWorkspace` method was removed in the commit [`gnome-shell/a8dcfa46`](https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/a8dcfa4656e01764380d081d74365092f08c114e) (the whole class was rewritten), so we need to find an alternative way to do this.
